import { FormEvent, useEffect, useRef, useState } from 'react';
import PortalHeader from './PortalHeader';

type Idea = { id: string; revision:number;title: string; features: string[]; milestones: Array<{ position: number; title: string; estimated_minutes: number;visible_result:boolean;required_activity_slug:string;required_skill:string }>; scope_reduced: boolean;feasibility_reasons:string[];excluded_features:Array<{feature:string;reason_code:string}>;source_kind:string;repository_url:string|null;repository_revision:string|null;ownership_basis:string|null;license_identifier:string|null;lineage_id:string;restored_from_id:string|null };
const csrf = () => document.cookie.split(';').map((v) => v.trim()).find((v) => v.startsWith('alpha_csrf='))?.slice(11) ?? '';
const skillLabels:Record<string,string>={algorithmic_reasoning:'알고리즘 추론',code_literacy:'코드 이해',docs_learning:'문서 학습',independent_coding:'독립 구현'};
const policyLabels:Record<string,string>={guided_ai:'단계형 AI',socratic_ai:'질문형 AI',documentation_navigator:'문서 탐색 안내',curated_documentation:'선별 문서',cheat_sheet_only:'치트 시트만',independent:'독립 수행',transfer_challenge:'전이 과제'};

function ProjectIdeationPage() {
  const [idea, setIdea] = useState<Idea | null>(null); const [message, setMessage] = useState('');
  const [title, setTitle] = useState('나만의 학습 기록 앱'); const [features, setFeatures] = useState('학습 기록,목록,통계,친구,랭킹,채팅');
  const [motivation,setMotivation]=useState('학습 과정을 직접 확인하고 싶음');const[targetUser,setTargetUser]=useState('혼자 공부하는 학습자');const[intendedOutcome,setIntendedOutcome]=useState('오늘의 학습 기록 확인');const[coreFeature,setCoreFeature]=useState('학습 기록');const[technology,setTechnology]=useState('typescript');const[weeklyMinutes,setWeeklyMinutes]=useState(120);
  const [policy,setPolicy]=useState('documentation_navigator');const[skillLevel,setSkillLevel]=useState('beginner');const[runtime,setRuntime]=useState('browser');const[infrastructure,setInfrastructure]=useState('local_only');
  const [sourceKind,setSourceKind]=useState('original');const[repositoryUrl,setRepositoryUrl]=useState('');const[repositoryRevision,setRepositoryRevision]=useState('');const[ownershipBasis,setOwnershipBasis]=useState('learner_owned');const[licenseIdentifier,setLicenseIdentifier]=useState('MIT');
  const ideaKey = useRef(crypto.randomUUID()); const projectKey = useRef(crypto.randomUUID());
  const confirmKey=useRef(crypto.randomUUID());const[confirmed,setConfirmed]=useState(false);
  const [history,setHistory]=useState<Idea[]>([]);const restoreKeys=useRef<Record<string,string>>({});
  const loadHistory=()=>fetch('/api/v1/projects/ideas',{credentials:'include'}).then((r)=>r.ok?r.json():null).then((body)=>body&&setHistory(body.ideas)).catch(()=>undefined);
  useEffect(()=>{void loadHistory();},[]);
  const changed=()=>{setIdea(null);setConfirmed(false);ideaKey.current=crypto.randomUUID();projectKey.current=crypto.randomUUID();};
  const submit = async (event: FormEvent) => { event.preventDefault();const normalizedCore=coreFeature.trim();const requestedFeatures=features.split(',').map((v) => v.trim()).filter(Boolean);if(!normalizedCore||!requestedFeatures.includes(normalizedCore)){setMessage('핵심 기능을 원하는 기능 목록에 포함해 주세요.');return;}
    const imported=sourceKind==='imported';const response = await fetch('/api/v1/projects/ideas', { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify({ title, motivation,target_user:targetUser,intended_outcome:intendedOutcome,core_feature:normalizedCore,technology,weekly_minutes:weeklyMinutes,requested_features:requestedFeatures, assistance_policy:policy,skill_level:skillLevel,runtime,infrastructure,source_kind:sourceKind,repository_url:imported?repositoryUrl:null,repository_revision:imported?repositoryRevision:null,ownership_basis:imported?ownershipBasis:null,license_identifier:imported?licenseIdentifier:null, idempotency_key: ideaKey.current }) });
    const body = await response.json(); if (!response.ok) { setMessage(body.error?.message ?? '아이디어를 만들지 못했습니다.'); return; } setIdea(body);setConfirmed(false);projectKey.current=crypto.randomUUID();confirmKey.current=crypto.randomUUID();void loadHistory();
  };
  const confirm=async()=>{if(!idea)return;const response=await fetch(`/api/v1/projects/ideas/${idea.id}/confirm`,{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-csrf-token':csrf()},body:JSON.stringify({scoped_features:idea.features,milestones:idea.milestones,idempotency_key:confirmKey.current})});if(response.ok)setConfirmed(true);else setMessage('범위를 확정하지 못했습니다.');};
  const start = async () => { if (!idea) return; const response = await fetch('/api/v1/projects', { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify({ idea_id: idea.id, idempotency_key: projectKey.current }) }); const body = await response.json(); if (response.ok) window.location.assign(`/projects/workspace?id=${body.id}`); else setMessage(body.error?.message ?? '프로젝트를 시작하지 못했습니다.'); };
  const restore=async(source:Idea)=>{restoreKeys.current[source.id]??=crypto.randomUUID();const response=await fetch(`/api/v1/projects/ideas/${source.id}/restore`,{method:'POST',credentials:'include',headers:{'content-type':'application/json','x-csrf-token':csrf()},body:JSON.stringify({idempotency_key:restoreKeys.current[source.id]})});const body=await response.json();if(response.ok){setIdea(body);setConfirmed(false);setMessage(`${source.revision}번 아이디어를 새 리비전으로 복원했습니다.`);void loadHistory();}else setMessage(body.error?.message??'아이디어를 복원하지 못했습니다.');};
  return <div className="learning-page"><PortalHeader /><main className="path-panel project-learning-panel"><p className="eyebrow">프로젝트 아이디어 스튜디오</p><h1>관심을 작은 결과로</h1>
    <form className="project-form" onSubmit={submit}><label>프로젝트 이름<input value={title} maxLength={120} onChange={(e) => { setTitle(e.target.value);changed(); }} required /></label><label>원하는 기능(쉼표로 구분)<textarea value={features} maxLength={1000} onChange={(e) => { setFeatures(e.target.value);changed(); }} required /></label>
      <label>만들고 싶은 이유<textarea value={motivation} maxLength={500} onChange={(e)=>{setMotivation(e.target.value);changed();}} required /></label><label>대상 사용자<input value={targetUser} maxLength={200} onChange={(e)=>{setTargetUser(e.target.value);changed();}} required /></label><label>의도한 결과<input value={intendedOutcome} maxLength={300} onChange={(e)=>{setIntendedOutcome(e.target.value);changed();}} required /></label><label>핵심 기능<input value={coreFeature} maxLength={120} onChange={(e)=>{const next=e.target.value;setCoreFeature(next);const values=features.split(',').map((v)=>v.trim());if(next.trim()&&!values.includes(next.trim()))setFeatures([next.trim(),...values.filter(Boolean)].join(','));changed();}} required /></label><label>기술<input value={technology} pattern="[a-z0-9+#.\-]+" maxLength={32} onChange={(e)=>{setTechnology(e.target.value);changed();}} required /></label><label>주간 프로젝트 시간(분)<input type="number" min={30} max={2400} value={weeklyMinutes} onChange={(e)=>{setWeeklyMinutes(Number(e.target.value));changed();}} required /></label>
      <label>도움 정책<select value={policy} onChange={(e)=>{setPolicy(e.target.value);changed();}}>{Object.entries(policyLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
      <label>숙련도<select value={skillLevel} onChange={(e)=>{setSkillLevel(e.target.value);changed();}}><option value="beginner">초급</option><option value="intermediate">중급</option><option value="advanced">고급</option></select></label>
      <label>실행 환경<select value={runtime} onChange={(e)=>{setRuntime(e.target.value);changed();}}><option value="browser">브라우저</option><option value="cli">CLI</option><option value="server">서버</option></select></label>
      <label>인프라<select value={infrastructure} onChange={(e)=>{setInfrastructure(e.target.value);changed();}}><option value="local_only">로컬만</option><option value="container_available">컨테이너 사용</option></select></label>
      <label>소스 종류<select value={sourceKind} onChange={(e)=>{setSourceKind(e.target.value);if(e.target.value==='original'){setRepositoryUrl('');setRepositoryRevision('');setOwnershipBasis('learner_owned');setLicenseIdentifier('MIT');}changed();}}><option value="original">직접 시작</option><option value="imported">저장소 가져오기</option></select></label>
      {sourceKind==='imported'&&<><label>저장소 URL<input type="url" value={repositoryUrl} pattern="https://.*" onChange={(e)=>{setRepositoryUrl(e.target.value);changed();}} required /></label><label>고정 리비전<input value={repositoryRevision} pattern="([0-9a-f]{40}|[0-9a-f]{64})" onChange={(e)=>{setRepositoryRevision(e.target.value);changed();}} required /></label><label>소유권 근거<select value={ownershipBasis} onChange={(e)=>{setOwnershipBasis(e.target.value);changed();}}><option value="learner_owned">학습자 소유</option><option value="authorized_import">가져오기 허가</option></select></label><label>라이선스 식별자<input value={licenseIdentifier} pattern="[A-Za-z0-9.\-]{2,40}" onChange={(e)=>{setLicenseIdentifier(e.target.value);changed();}} required /></label></>}
      <button className="primary-action" type="submit">실행 가능한 범위 확인</button></form>
    {idea && <section className="project-result" aria-live="polite"><p className="status-dot">AI 없이 결정론적 범위 검사 완료</p><h2>{idea.title}</h2>{idea.source_kind==='imported'&&<p>가져온 저장소: {idea.repository_url} · 리비전 {idea.repository_revision} · {idea.ownership_basis} · {idea.license_identifier}</p>}{idea.scope_reduced && <p>첫 버전에 필요한 기능으로 줄였습니다. 최종 선택은 학습자가 확정합니다.</p>}<p>판정 이유: {idea.feasibility_reasons.join(' · ')}</p>{idea.excluded_features.map((item)=><p key={item.feature}>{item.feature} 제외 · {item.reason_code}</p>)}<ul>{idea.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><ol>{idea.milestones.map((m) => <li key={m.position}><strong>{m.title}</strong><span>{m.estimated_minutes}분 · 보이는 결과 · 역량 {skillLabels[m.required_skill]} · 활동 {m.required_activity_slug}</span></li>)}</ol>{!confirmed?<button type="button" onClick={confirm}>이 범위 확정</button>:<button type="button" onClick={start}>이 프로젝트 선택</button>}</section>}
    {message && <p role="alert" className="auth-message">{message}</p>}{history.length>0&&<section className="project-result"><h2>아이디어 리비전 기록</h2><ol>{history.map((item)=><li key={item.id}><span>{item.revision} · {item.title}{item.restored_from_id?' · 복원본':''}</span>{item.source_kind==='imported'&&<span>{item.repository_url} · {item.repository_revision} · {item.license_identifier}</span>}<button type="button" onClick={()=>restore(item)}>이 아이디어 복원</button></li>)}</ol></section>}</main></div>;
}
export default ProjectIdeationPage;
