import { useEffect, useRef, useState } from "react";

type Review = { id:string; revision:number; state:string; artifact_hash:string; updated_at:string };
type Detail = Review & {
  artifact:unknown; provenance?:Record<string,unknown>|null;
  ai_receipts:Array<Record<string,unknown>>; human_receipts:Array<Record<string,unknown>>;
  rights_receipts:Array<Record<string,unknown>>; pilot_receipts:Array<Record<string,unknown>>;
  audit:Array<Record<string,unknown>>;
};
const labels:Record<string,string>={ai_review_pending:"AI 검토 대기",changes_requested:"변경 요청",human_review_pending:"사람 검토 대기",rights_review_pending:"권리 검토 대기",pilot_pending:"파일럿 대기",approved:"게시 승인",published:"게시 중",unpublished:"게시 해제",removal_pending:"제거 대기",removal_completed:"제거 완료",rejected:"거절"};
const csrf=()=>document.cookie.split(";").map(v=>v.trim()).find(v=>v.startsWith("alpha_csrf="))?.slice(11)??"";

export default function ReviewWorkspacePage(){
  const [reviews,setReviews]=useState<Review[]>([]),[detail,setDetail]=useState<Detail|null>(null),[message,setMessage]=useState("");
  const [note,setNote]=useState(""),[evidence,setEvidence]=useState(""),[terms,setTerms]=useState(""),[rightsBasis,setRightsBasis]=useState("contract");
  const [commercial,setCommercial]=useState(false),[redistribution,setRedistribution]=useState(false);
  const [candidateArtifact,setCandidateArtifact]=useState(""),[impact,setImpact]=useState("standard"),[revisionArtifact,setRevisionArtifact]=useState("");
  const [licenseId,setLicenseId]=useState(""),[attribution,setAttribution]=useState(""),[evidenceRef,setEvidenceRef]=useState(""),[evidenceHash,setEvidenceHash]=useState("");
  const [cohort,setCohort]=useState(""),[pilotSource,setPilotSource]=useState(""),[pilotStart,setPilotStart]=useState(""),[pilotEnd,setPilotEnd]=useState(""),[participants,setParticipants]=useState(""),[completion,setCompletion]=useState(""),[failure,setFailure]=useState(""),[reports,setReports]=useState(""),[rollback,setRollback]=useState(false),[rollbackEvidence,setRollbackEvidence]=useState(""),[pilotNote,setPilotNote]=useState("");
  const [removalReason,setRemovalReason]=useState(""),[removalEvidence,setRemovalEvidence]=useState("");
  const keys=useRef(new Map<string,string>());
  const stableKey=(signature:string)=>{let key=keys.current.get(signature);if(!key){key=crypto.randomUUID();keys.current.set(signature,key);}return key;};
  const load=async()=>{try{const response=await fetch("/api/v1/content/reviews",{credentials:"include"});if(!response.ok)throw new Error("검토 목록 접근 권한이 없습니다.");setReviews((await response.json()).reviews??[]);}catch(error){setMessage(error instanceof Error?error.message:"목록을 불러오지 못했습니다.");}};
  const open=async(id:string)=>{const response=await fetch(`/api/v1/content/reviews/${id}`,{credentials:"include"});if(!response.ok){setMessage("검토 상세를 불러오지 못했습니다.");return;}setDetail(await response.json());};
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>{if(!detail?.id)return;const id=detail.id;const timer=window.setInterval(()=>void open(id),3000);return()=>window.clearInterval(timer);},[detail?.id]);
  const request=async(path:string,body:Record<string,unknown>)=>{if(!detail)return;const signature=`${detail.id}:${path}:${JSON.stringify(body)}`,idempotency_key=stableKey(signature);try{const response=await fetch(`/api/v1/content/reviews/${detail.id}/${path}`,{method:"POST",credentials:"include",headers:{"content-type":"application/json","x-csrf-token":csrf()},body:JSON.stringify({...body,idempotency_key})});const payload=await response.json();if(!response.ok){setMessage(payload.error?.message??"전이를 완료하지 못했습니다.");return;}keys.current.delete(signature);setMessage(labels[payload.state]??"증거가 기록됐습니다.");await load();await open(detail.id);}catch(error){setMessage(error instanceof Error?error.message:"응답을 받지 못했습니다.");}};
  const createReview=async()=>{const body={artifact_id:candidateArtifact,impact},signature=`create:${JSON.stringify(body)}`,idempotency_key=stableKey(signature);try{const response=await fetch("/api/v1/content/reviews",{method:"POST",credentials:"include",headers:{"content-type":"application/json","x-csrf-token":csrf()},body:JSON.stringify({...body,idempotency_key})});const payload=await response.json();if(!response.ok){setMessage(payload.error?.message??"검토를 시작하지 못했습니다.");return;}keys.current.delete(signature);await load();await open(payload.id);}catch(error){setMessage(error instanceof Error?error.message:"응답을 받지 못했습니다.");}};
  const provenanceBody={origin_type:"ai_generated",creator_or_provider:"서버 파생",source_url:null,source_revision:"서버 파생",license_basis:"provider_contract",license_identifier:licenseId,attribution,modification_status:"generated",commercial_use_allowed:commercial,redistribution_allowed:redistribution,evidence_reference:evidenceRef,evidence_hash:evidenceHash,attachment_metadata:{record_type:"generation_evidence"},legal_status:"pending"};
  const pilotBody={cohort,source_reference:pilotSource,started_at:pilotStart?new Date(pilotStart).toISOString():"",ended_at:pilotEnd?new Date(pilotEnd).toISOString():"",participants:Number(participants),completion_rate:Number(completion),failure_rate:Number(failure),report_count:Number(reports),rollback_ready:rollback,rollback_evidence:rollbackEvidence,note:pilotNote};
  return <main className="review-workspace"><header className="review-hero"><div><p className="eyebrow">증거 기반 게시 파이프라인</p><h1>콘텐츠 검토 작업대</h1><p>불변 리비전마다 독립 AI 3회, 사람, 권리, 파일럿 증거를 순서대로 확인합니다.</p></div><a className="secondary-action" href="/content-studio">생성 작업으로</a></header><p className="blocked-badge">외부 AI 검토 실행은 구성되지 않아 차단됨 · 신뢰된 운영자 영수증만 수락</p>{message&&<p role="status" className="form-message">{message}</p>}
    <section className="review-layout" aria-label="검토 대기열"><div className="review-list"><h2>대기열</h2><fieldset><legend>생성 산출물 검토 시작</legend><label>후보 아티팩트 UUID<input value={candidateArtifact} onChange={event=>setCandidateArtifact(event.target.value)}/></label><label>영향 수준<select value={impact} onChange={event=>setImpact(event.target.value)}><option value="standard">일반 · 권리 승인 후 게시 승인</option><option value="high">고영향 · 파일럿 필수</option><option value="novel">신규 · 파일럿 필수</option></select></label><button type="button" onClick={()=>void createReview()}>검토 시작</button></fieldset>{reviews.length===0&&<p>검토 대상이 없습니다.</p>}{reviews.map(item=><article key={item.id} className="review-card"><strong>{labels[item.state]??item.state}</strong><span>리비전 {item.revision}</span><code>{item.artifact_hash.slice(0,12)}</code><button type="button" onClick={()=>void open(item.id)}>검토 열기</button></article>)}</div>
      <div className="review-detail">{!detail?<p>대기열에서 검토 대상을 선택하세요.</p>:<><div className="review-detail__head"><h2>{labels[detail.state]??detail.state}</h2><span>리비전 {detail.revision}</span></div><p><code>입력 SHA-256 {detail.artifact_hash}</code></p><pre aria-label="검토 아티팩트">{JSON.stringify(detail.artifact,null,2)}</pre>
        <h3>독립 AI 검토 영수증</h3>{detail.ai_receipts.length===0?<p>영수증이 없습니다. 자동 성공으로 표시하지 않습니다.</p>:detail.ai_receipts.map(receipt=><article className="evidence-card" key={String(receipt.id)}><strong>{String(receipt.kind)} · {String(receipt.outcome)}</strong><p>{String(receipt.provider)}/{String(receipt.model)} · seed {String(receipt.review_seed)}</p><pre>{JSON.stringify({context:receipt.review_context,response:receipt.review_response,findings:receipt.findings},null,2)}</pre></article>)}
        <h3>출처·권리 증거</h3>{detail.provenance?<pre>{JSON.stringify(detail.provenance,null,2)}</pre>:<fieldset><legend>AI 생성 출처 기록</legend><p>실제 provider/model/job/attempt/run과 source revision은 서버가 현재 산출물에서 파생합니다.</p><label>제공자 계약/약관 식별자<input value={licenseId} onChange={event=>setLicenseId(event.target.value)}/></label><label>표시·귀속 문구<textarea value={attribution} onChange={event=>setAttribution(event.target.value)}/></label><label>증거 참조<input value={evidenceRef} onChange={event=>setEvidenceRef(event.target.value)}/></label><label>증거 SHA-256<input value={evidenceHash} onChange={event=>setEvidenceHash(event.target.value)}/></label><label><input type="checkbox" checked={commercial} onChange={event=>setCommercial(event.target.checked)}/> 상업 이용 허용</label><label><input type="checkbox" checked={redistribution} onChange={event=>setRedistribution(event.target.checked)}/> 재배포 허용</label><button type="button" onClick={()=>void request("provenance",provenanceBody)}>출처 증거 기록</button></fieldset>}
        {detail.state==="human_review_pending"&&<fieldset><legend>사람 검토</legend><label>사람 검토 근거<textarea value={note} onChange={event=>setNote(event.target.value)}/></label><div className="button-row"><button type="button" onClick={()=>void request("human",{decision:"approve",note})}>사람 승인</button><button type="button" onClick={()=>void request("human",{decision:"changes_requested",note})}>변경 요청</button></div></fieldset>}
        {detail.state==="rights_review_pending"&&<fieldset><legend>권리 검토</legend><label>권리 근거<select value={rightsBasis} onChange={event=>setRightsBasis(event.target.value)}><option value="contract">제공자 계약</option><option value="original">원저작권</option><option value="licensed">라이선스</option><option value="public_domain">퍼블릭 도메인</option></select></label><label>검토 증거<textarea value={evidence} onChange={event=>setEvidence(event.target.value)}/></label><label>제공자 약관 버전<input value={terms} onChange={event=>setTerms(event.target.value)}/></label><label><input type="checkbox" checked={commercial} onChange={event=>setCommercial(event.target.checked)}/> 상업 이용 허용 확인</label><label><input type="checkbox" checked={redistribution} onChange={event=>setRedistribution(event.target.checked)}/> 재배포 허용 확인</label><div className="button-row"><button type="button" disabled={!detail.provenance||!commercial||!redistribution} onClick={()=>void request("rights",{provenance_id:detail.provenance?.id,provenance_hash:detail.provenance?.provenance_hash,decision:"approve",basis:rightsBasis,evidence,commercial_use_allowed:commercial,redistribution_allowed:redistribution,provider_terms_version:terms})}>권리 승인</button><button type="button" disabled={!detail.provenance} onClick={()=>void request("rights",{provenance_id:detail.provenance?.id,provenance_hash:detail.provenance?.provenance_hash,decision:"reject",basis:rightsBasis,evidence,commercial_use_allowed:false,redistribution_allowed:false,provider_terms_version:terms})}>권리 거절</button></div></fieldset>}
        {detail.state==="pilot_pending"&&<fieldset><legend>고영향·신규 콘텐츠 파일럿</legend><label>코호트<input value={cohort} onChange={event=>setCohort(event.target.value)}/></label><label>측정 원본/실행 참조<input value={pilotSource} onChange={event=>setPilotSource(event.target.value)}/></label><label>시작 시각<input type="datetime-local" value={pilotStart} onChange={event=>setPilotStart(event.target.value)}/></label><label>종료 시각<input type="datetime-local" value={pilotEnd} onChange={event=>setPilotEnd(event.target.value)}/></label><label>참여자 수<input type="number" min="5" value={participants} onChange={event=>setParticipants(event.target.value)}/></label><label>완료율 0~1<input type="number" min="0" max="1" step="0.01" value={completion} onChange={event=>setCompletion(event.target.value)}/></label><label>실패율 0~1<input type="number" min="0" max="1" step="0.01" value={failure} onChange={event=>setFailure(event.target.value)}/></label><label>신고 수<input type="number" min="0" value={reports} onChange={event=>setReports(event.target.value)}/></label><label><input type="checkbox" checked={rollback} onChange={event=>setRollback(event.target.checked)}/> 즉시 롤백 준비</label><label>롤백 증거<textarea value={rollbackEvidence} onChange={event=>setRollbackEvidence(event.target.value)}/></label><label>파일럿 판단 근거<textarea value={pilotNote} onChange={event=>setPilotNote(event.target.value)}/></label><div className="button-row"><button type="button" onClick={()=>void request("pilot",{...pilotBody,decision:"pass"})}>파일럿 통과 기록</button><button type="button" onClick={()=>void request("pilot",{...pilotBody,decision:"fail"})}>파일럿 실패 기록</button></div></fieldset>}
        {detail.state==="changes_requested"||detail.state==="unpublished"||detail.state==="removal_completed"?<fieldset><legend>새 불변 리비전</legend><label>새 아티팩트 UUID<input value={revisionArtifact} onChange={event=>setRevisionArtifact(event.target.value)}/></label><button type="button" onClick={()=>void request("revise",{artifact_id:revisionArtifact})}>AI 검토부터 다시 시작</button></fieldset>:null}
        {detail.state==="approved"&&<button type="button" onClick={()=>void request("publish",{})}>정확한 승인 리비전 게시</button>}{detail.state==="published"&&<div className="button-row"><button type="button" onClick={()=>void request("unpublish",{reason:"운영자 게시 해제"})}>즉시 게시 해제</button><button type="button" onClick={()=>void request("removal",{reason:"권리 제거 요청"})}>제거 대기 전환</button></div>}{detail.state==="removal_pending"&&<fieldset><legend>제거 완료 증거</legend><label>제거 사유<input value={removalReason} onChange={event=>setRemovalReason(event.target.value)}/></label><label>제거 확인 증거<textarea value={removalEvidence} onChange={event=>setRemovalEvidence(event.target.value)}/></label><button type="button" onClick={()=>void request("removal/complete",{reason:removalReason,evidence:removalEvidence})}>제거 완료 기록</button></fieldset>}
        <h3>사람·권리·파일럿·감사 증거</h3><pre>{JSON.stringify({human:detail.human_receipts,rights:detail.rights_receipts,pilot:detail.pilot_receipts,audit:detail.audit},null,2)}</pre></>}</div></section></main>;
}
