import { useEffect,useState } from "react";
type Review={id:string;revision:number;state:string;artifact_hash:string;updated_at:string};
type Detail=Review&{artifact:unknown;ai_receipts:Array<{kind:string;outcome:string;provider:string;model:string;prompt_version:string;latency_ms:number;usage:unknown}>};
const labels:Record<string,string>={ai_review_pending:"AI 검토 대기",changes_requested:"변경 요청",human_review_pending:"사람 검토 대기",rights_review_pending:"권리 검토 대기",pilot_pending:"파일럿 대기",approved:"게시 승인",published:"게시 중",unpublished:"게시 해제",removal_pending:"제거 대기",rejected:"거절"};
const csrf=()=>document.cookie.split(";").map(v=>v.trim()).find(v=>v.startsWith("alpha_csrf="))?.slice(11)??"";
export default function ReviewWorkspacePage(){
 const [reviews,setReviews]=useState<Review[]>([]),[detail,setDetail]=useState<Detail|null>(null),[message,setMessage]=useState("");const [note,setNote]=useState(""),[evidence,setEvidence]=useState(""),[terms,setTerms]=useState("");const [commercial,setCommercial]=useState(false),[redistribution,setRedistribution]=useState(false),[rollback,setRollback]=useState(false);const [cohort,setCohort]=useState(""),[revisionArtifact,setRevisionArtifact]=useState(""),[candidateArtifact,setCandidateArtifact]=useState(""),[impact,setImpact]=useState("standard");
 const load=async()=>{try{const r=await fetch("/api/v1/content/reviews",{credentials:"include"});if(!r.ok)throw new Error("검토 목록 접근 권한이 없습니다.");setReviews((await r.json()).reviews??[]);}catch(e){setMessage(e instanceof Error?e.message:"목록을 불러오지 못했습니다.");}};
 const open=async(id:string)=>{const r=await fetch(`/api/v1/content/reviews/${id}`,{credentials:"include"});if(!r.ok){setMessage("검토 상세를 불러오지 못했습니다.");return;}setDetail(await r.json());};
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(timer);},[]);
 const act=async(path:string,body:Record<string,unknown>)=>{if(!detail)return;const r=await fetch(`/api/v1/content/reviews/${detail.id}/${path}`,{method:"POST",credentials:"include",headers:{"content-type":"application/json","x-csrf-token":csrf()},body:JSON.stringify({...body,idempotency_key:crypto.randomUUID()})});const p=await r.json();if(!r.ok){setMessage(p.error?.message??"전이를 완료하지 못했습니다.");return;}setDetail({...detail,state:p.state,revision:p.revision??detail.revision});setMessage(labels[p.state]??p.state);await load();};
 const createReview=async()=>{const r=await fetch("/api/v1/content/reviews",{method:"POST",credentials:"include",headers:{"content-type":"application/json","x-csrf-token":csrf()},body:JSON.stringify({artifact_id:candidateArtifact,impact,idempotency_key:crypto.randomUUID()})});const p=await r.json();if(!r.ok){setMessage(p.error?.message??"검토를 시작하지 못했습니다.");return;}setMessage("AI 검토 대기");await load();await open(p.id);};
 return <main className="review-workspace"><header className="review-hero"><div><p className="eyebrow">증거 기반 게시 파이프라인</p><h1>콘텐츠 검토 작업대</h1><p>불변 리비전마다 독립 AI 3회, 사람, 권리, 파일럿 증거를 순서대로 확인합니다.</p></div><a className="secondary-action" href="/content-studio">생성 작업으로</a></header><p className="blocked-badge">외부 AI 검토 실행은 구성되지 않아 차단됨 · 신뢰된 운영자 영수증만 수락</p>{message&&<p role="status" className="form-message">{message}</p>}
 <section className="review-layout" aria-label="검토 대기열"><div className="review-list"><h2>대기열</h2><fieldset><legend>생성 산출물 검토 시작</legend><label>후보 아티팩트 UUID<input value={candidateArtifact} onChange={e=>setCandidateArtifact(e.target.value)}/></label><label>영향 수준<select value={impact} onChange={e=>setImpact(e.target.value)}><option value="standard">일반 · 권리 승인 후 게시 승인</option><option value="high">고영향 · 파일럿 필수</option><option value="novel">신규 · 파일럿 필수</option></select></label><button type="button" onClick={()=>void createReview()}>검토 시작</button></fieldset>{reviews.length===0&&<p>검토 대상이 없습니다.</p>}{reviews.map(item=><article key={item.id} className="review-card"><strong>{labels[item.state]??item.state}</strong><span>리비전 {item.revision}</span><code>{item.artifact_hash.slice(0,12)}</code><button type="button" onClick={()=>void open(item.id)}>검토 열기</button></article>)}</div>
 <div className="review-detail">{!detail?<p>대기열에서 검토 대상을 선택하세요.</p>:<><div className="review-detail__head"><h2>{labels[detail.state]??detail.state}</h2><span>리비전 {detail.revision}</span></div><p><code>입력 SHA-256 {detail.artifact_hash}</code></p><pre aria-label="검토 아티팩트">{JSON.stringify(detail.artifact,null,2)}</pre><h3>독립 AI 검토 영수증</h3>{detail.ai_receipts.length===0?<p>영수증이 없습니다. 자동 성공으로 표시하지 않습니다.</p>:<ul>{detail.ai_receipts.map(r=><li key={r.kind}><strong>{r.kind}</strong> · {r.outcome} · {r.provider}/{r.model} · {r.latency_ms}ms</li>)}</ul>}
 {detail.state==="human_review_pending"&&<fieldset><legend>사람 검토</legend><label>사람 검토 근거<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div className="button-row"><button type="button" onClick={()=>void act("human",{decision:"approve",note})}>사람 승인</button><button type="button" onClick={()=>void act("human",{decision:"changes_requested",note})}>변경 요청</button></div></fieldset>}
 {detail.state==="rights_review_pending"&&<fieldset><legend>권리 검토</legend><label>권리 근거<textarea value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><label>제공자 약관 버전<input value={terms} onChange={e=>setTerms(e.target.value)}/></label><label><input type="checkbox" checked={commercial} onChange={e=>setCommercial(e.target.checked)}/> 상업 이용 허용</label><label><input type="checkbox" checked={redistribution} onChange={e=>setRedistribution(e.target.checked)}/> 재배포 허용</label><div className="button-row"><button type="button" disabled={!commercial||!redistribution} onClick={()=>void act("rights",{decision:"approve",basis:"original",evidence,commercial_use_allowed:commercial,redistribution_allowed:redistribution,provider_terms_version:terms})}>권리 승인</button><button type="button" onClick={()=>void act("rights",{decision:"reject",basis:"original",evidence,commercial_use_allowed:false,redistribution_allowed:false,provider_terms_version:terms})}>권리 거절</button></div></fieldset>}
 {detail.state==="pilot_pending"&&<fieldset><legend>고영향·신규 콘텐츠 파일럿</legend><label>코호트<input value={cohort} onChange={e=>setCohort(e.target.value)}/></label><label><input type="checkbox" checked={rollback} onChange={e=>setRollback(e.target.checked)}/> 즉시 롤백 준비</label><div className="button-row"><button type="button" disabled={!rollback} onClick={()=>void act("pilot",{cohort,started_at:new Date(Date.now()-86400000).toISOString(),ended_at:new Date().toISOString(),participants:5,completion_rate:.6,failure_rate:.3,report_count:0,rollback_ready:rollback,decision:"pass",note:"파일럿 기준 충족"})}>파일럿 통과</button><button type="button" onClick={()=>void act("pilot",{cohort,started_at:new Date(Date.now()-86400000).toISOString(),ended_at:new Date().toISOString(),participants:5,completion_rate:0,failure_rate:1,report_count:1,rollback_ready:rollback,decision:"fail",note:"파일럿 기준 미달"})}>파일럿 실패</button></div></fieldset>}
 {detail.state==="changes_requested"&&<fieldset><legend>새 불변 리비전</legend><label>새 아티팩트 UUID<input value={revisionArtifact} onChange={e=>setRevisionArtifact(e.target.value)}/></label><button type="button" onClick={()=>void act("revise",{artifact_id:revisionArtifact})}>AI 검토부터 다시 시작</button></fieldset>}{detail.state==="approved"&&<button type="button" onClick={()=>void act("publish",{})}>정확한 승인 리비전 게시</button>}{detail.state==="published"&&<div className="button-row"><button type="button" onClick={()=>void act("unpublish",{reason:"운영자 게시 해제"})}>즉시 게시 해제</button><button type="button" onClick={()=>void act("removal",{reason:"권리 제거 요청"})}>제거 대기 전환</button></div>}</>}</div></section></main>;
}
